#!/usr/bin/env python3
"""Plot a Fityk parameter table as a matrix of subplots.

The script reads a tab- or comma-separated table and plots one subplot per
(parameter, peak) pair. It is designed to work with reports generated by
FitykTools.lua, where columns often look like:

- center1, eCenter1
- height2, eHeight2
- hwhm3, eHwhm3

Usage examples:
    python plot_fityk_table.py parameters_report.txt --delimiter tab --x-column x --output fityk_matrix.png
    python plot_fityk_table.py results.csv --x-column temperature --output matrix.png
"""

import argparse
import csv
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple


PARAM_RE = re.compile(r"^(?P<error>e)?(?P<name>[A-Za-z_][A-Za-z0-9_]*?)(?P<peak>\d+)$")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot a Fityk parameter table as a matrix")
    parser.add_argument("input", help="Path to the saved table")
    parser.add_argument("--delimiter", default="auto", help="Delimiter: tab, comma, or auto")
    parser.add_argument("--x-column", default=None, help="Column to use for the x-axis values")
    parser.add_argument("--output", default=None, help="Output image path (PNG). Defaults to <input>_matrix.png and opens it automatically")
    parser.add_argument("--dpi", type=int, default=150, help="Output DPI when saving")
    parser.add_argument("--no-errors", action="store_true", help="Ignore error columns")
    parser.add_argument("--no-open", action="store_true", help="Do not open the generated plot automatically")
    return parser.parse_args()


def normalize_delimiter(delimiter: str) -> str:
    value = (delimiter or "").strip().lower()
    if value in {"", "auto"}:
        return "auto"
    if value in {"tab", "\\t", "\t"}:
        return "\t"
    if value in {"comma", ",", "csv"}:
        return ","
    return delimiter


def detect_delimiter(path: Path) -> str:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        sample = handle.read(4096)

    if "," in sample and "\t" not in sample:
        return ","
    if "\t" in sample and "," not in sample:
        return "\t"

    try:
        dialect = csv.Sniffer().sniff(sample, delimiters=",\t")
        return dialect.delimiter
    except csv.Error:
        return "\t"


def load_fityk_config(table_path: Path) -> Dict[str, str]:
    config_path = table_path.parent / "fityk_config.lua"
    if not config_path.exists():
        return {}

    try:
        text = config_path.read_text(encoding="utf-8-sig")
    except OSError:
        return {}

    config: Dict[str, str] = {}
    match = re.search(r'output_delimiter\s*=\s*"([^"]+)"', text)
    if match:
        config["output_delimiter"] = match.group(1).strip().upper()

    match = re.search(r'report_output_file\s*=\s*"([^"]*)"', text)
    if match:
        config["report_output_file"] = match.group(1).strip()

    return config


def resolve_output_path(input_path: Path, requested_output: Optional[str], config: Dict[str, str]) -> Path:
    if requested_output:
        output_path = Path(requested_output).expanduser()
        if not output_path.is_absolute():
            output_path = (input_path.parent / output_path).resolve()
        return output_path.with_suffix(".png") if output_path.suffix.lower() not in {".png", ".jpg", ".jpeg", ".svg", ".pdf"} else output_path

    if config.get("report_output_file"):
        output_path = Path(config["report_output_file"]).expanduser()
        if not output_path.is_absolute():
            output_path = (input_path.parent / output_path).resolve()
        return output_path.with_suffix(".png") if output_path.suffix.lower() not in {".png", ".jpg", ".jpeg", ".svg", ".pdf"} else output_path

    return input_path.with_name(f"{input_path.stem}_matrix.png")


def open_output(path: Path) -> None:
    if not path.exists():
        return

    try:
        if sys.platform.startswith("win"):
            os.startfile(path)  # type: ignore[attr-defined]
        elif sys.platform == "darwin":
            subprocess.Popen(["open", str(path)])
        else:
            subprocess.Popen(["xdg-open", str(path)])
    except OSError:
        print(f"Could not open plot automatically: {path}")


def parse_table(path: Path, delimiter: str) -> Tuple[List[str], List[List[str]]]:
    rows: List[List[str]] = []
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.reader(handle, delimiter=delimiter)
        for row in reader:
            if not row:
                continue
            if all(not cell.strip() for cell in row):
                continue
            if row[0].lstrip().startswith("#"):
                continue
            rows.append([cell.strip() for cell in row])

    if not rows:
        raise ValueError("No data rows found in input table")

    header = rows[0]
    data_rows = rows[1:]
    return header, data_rows


def to_float(value: str) -> Optional[float]:
    text = (value or "").strip()
    if not text or text.lower() in {"nan", "none", "null", "na", "-"}:
        return None
    try:
        return float(text)
    except ValueError:
        return None


def coerce_x_value(raw_value: object) -> object:
    if raw_value is None:
        return None
    text = str(raw_value).strip()
    if not text or text.lower() in {"nan", "none", "null", "na", "-"}:
        return None
    try:
        return float(text)
    except ValueError:
        return text


def find_x_column(header: Sequence[str], requested: Optional[str], data_rows: Sequence[Sequence[str]]) -> Tuple[Optional[str], List[object]]:
    if requested:
        if requested not in header:
            raise ValueError(f"Requested x-column '{requested}' not found in header")
        x_index = header.index(requested)
        values = [coerce_x_value(row[x_index]) if x_index < len(row) else None for row in data_rows]
        return requested, values

    preferred_names = {"x", "xvalue", "x_value", "xaxis", "energy", "wavelength", "temperature", "time"}
    for name in header:
        if name.lower() in preferred_names:
            idx = header.index(name)
            values = [coerce_x_value(row[idx]) if idx < len(row) else None for row in data_rows]
            return name, values

    for idx, name in enumerate(header):
        if name.lower() in {"file", "filename", "dataset", "name", "label"}:
            values = [coerce_x_value(row[idx]) if idx < len(row) else None for row in data_rows]
            if any(value is not None for value in values):
                return name, values
            continue
        if not PARAM_RE.match(name):
            values = [coerce_x_value(row[idx]) if idx < len(row) else None for row in data_rows]
            if any(value is not None for value in values):
                return name, values

    return header[0] if header else "row_index", [coerce_x_value(row[0]) if row else None for row in data_rows]


def build_series_map(header: Sequence[str], data_rows: Sequence[Sequence[str]], ignore_errors: bool) -> Tuple[List[str], List[int], Dict[Tuple[str, int], Dict[str, Optional[int]]]]:
    series_map: Dict[Tuple[str, int], Dict[str, Optional[int]]] = {}

    for col_idx, name in enumerate(header):
        match = PARAM_RE.match(name)
        if not match:
            continue

        is_error = bool(match.group("error"))
        if is_error and ignore_errors:
            continue

        param_name = match.group("name").lower()
        peak_id = int(match.group("peak"))
        key = (param_name, peak_id)
        entry = series_map.setdefault(key, {"value_col": None, "error_col": None})

        if is_error:
            entry["error_col"] = col_idx
        else:
            entry["value_col"] = col_idx

    valid_keys = sorted(series_map.keys(), key=lambda item: (item[0], item[1]))
    param_names = sorted({param for param, _ in valid_keys})
    peaks = sorted({peak for _, peak in valid_keys})
    return param_names, peaks, {key: series_map[key] for key in valid_keys}


def collect_series_values(series_map: Dict[Tuple[str, int], Dict[str, Optional[int]]], data_rows: Sequence[Sequence[str]]) -> Dict[Tuple[str, int], Dict[str, List[Optional[float]]]]:
    result: Dict[Tuple[str, int], Dict[str, List[Optional[float]]]] = {}
    for key, cols in series_map.items():
        value_col = cols.get("value_col")
        error_col = cols.get("error_col")
        values: List[Optional[float]] = []
        errors: List[Optional[float]] = []

        for row in data_rows:
            val = to_float(row[value_col]) if value_col is not None and value_col < len(row) else None
            err = to_float(row[error_col]) if error_col is not None and error_col < len(row) else None
            values.append(val)
            errors.append(err)

        result[key] = {"value": values, "error": errors}
    return result


def plot_matrix(x_values: Sequence[object], series_values: Dict[Tuple[str, int], Dict[str, List[Optional[float]]]], param_names: Sequence[str], peaks: Sequence[int], output_path: Optional[Path], dpi: int) -> None:
    import matplotlib.pyplot as plt

    n_rows = len(param_names)
    n_cols = len(peaks)
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(3.2 * n_cols, 2.4 * n_rows), squeeze=False)
    fig.suptitle("Fityk parameter matrix")

    numeric_x = []
    category_labels: Optional[List[str]] = None
    category_map: Dict[str, int] = {}
    if x_values:
        numeric_candidate = True
        for value in x_values:
            if value is None:
                numeric_x.append(float("nan"))
                continue
            if isinstance(value, (int, float)):
                numeric_x.append(float(value))
                continue
            try:
                numeric_x.append(float(value))
            except (TypeError, ValueError):
                numeric_candidate = False
                text = str(value)
                if text not in category_map:
                    category_map[text] = len(category_map)
                numeric_x.append(float(category_map[text]))
        if not numeric_candidate:
            category_labels = [label for label, _ in sorted(category_map.items(), key=lambda item: item[1])]
        else:
            category_labels = None

    for row_idx, param_name in enumerate(param_names):
        for col_idx, peak_id in enumerate(peaks):
            ax = axes[row_idx][col_idx]
            key = (param_name, peak_id)
            if key not in series_values:
                ax.axis("off")
                continue

            values = series_values[key]["value"]
            errors = series_values[key]["error"]
            x_plot: List[float] = []
            y_plot: List[float] = []
            err_plot: List[float] = []

            for x_value, y_value, e_value in zip(x_values, values, errors):
                if x_value is None or y_value is None:
                    continue
                if category_labels is not None:
                    x_coord = category_map.get(str(x_value))
                    if x_coord is None:
                        continue
                    x_plot.append(float(x_coord))
                else:
                    x_plot.append(float(x_value))
                y_plot.append(float(y_value))
                if e_value is not None:
                    err_plot.append(float(e_value))
                else:
                    err_plot.append(0.0)

            if x_plot:
                if any(err != 0.0 for err in err_plot):
                    ax.errorbar(x_plot, y_plot, yerr=err_plot, fmt="o-", capsize=3, elinewidth=1.0)
                else:
                    ax.plot(x_plot, y_plot, "o-")
            else:
                ax.text(0.5, 0.5, "no data", ha="center", va="center", transform=ax.transAxes)

            ax.set_title(f"{param_name} {peak_id}")
            ax.grid(True, alpha=0.25)
            if category_labels is not None:
                ax.set_xticks(list(range(len(category_labels))))
                ax.set_xticklabels(category_labels, rotation=45, ha="right")
            if row_idx < n_rows - 1:
                ax.set_xlabel("")
            if col_idx > 0:
                ax.set_ylabel("")

    fig.tight_layout(rect=[0, 0, 1, 0.98])
    if output_path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
        print(f"Saved plot to {output_path}")
    else:
        plt.show()
    plt.close(fig)


def main() -> None:
    args = parse_args()
    input_path = Path(args.input).expanduser().resolve()
    if not input_path.exists():
        raise FileNotFoundError(f"Input file not found: {input_path}")

    config = load_fityk_config(input_path)
    delimiter = normalize_delimiter(args.delimiter)
    if delimiter == "auto":
        config_delimiter = config.get("output_delimiter")
        if config_delimiter in {"TAB", "CSV"}:
            delimiter = "\t" if config_delimiter == "TAB" else ","
        else:
            delimiter = detect_delimiter(input_path)
    header, data_rows = parse_table(input_path, delimiter)

    x_name, x_values = find_x_column(header, args.x_column, data_rows)
    if x_name is None:
        raise ValueError("Could not determine an x-axis column")

    param_names, peaks, series_map = build_series_map(header, data_rows, args.no_errors)
    if not series_map:
        raise ValueError("No parameter columns matching the Fityk naming pattern were found")

    series_values = collect_series_values(series_map, data_rows)
    output_path = resolve_output_path(input_path, args.output, config)
    plot_matrix(x_values, series_values, param_names, peaks, output_path, args.dpi)
    if not args.no_open:
        open_output(output_path)


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:  # pragma: no cover - CLI friendly error handling
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)
